services:
  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: valify
      POSTGRES_USER: valify
      POSTGRES_PASSWORD: valify
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
